<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Ryzom.Core\Ryzom.Core.csproj" />
    <ProjectReference Include="..\..\Ryzom.Engine\Ryzom.Engine.csproj" />
  </ItemGroup>

</Project>
